-- Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.
-- 方言：sqlite。表结构的唯一来源是 internal/base/schema 的注册表，改表先改注册表再重新生成。

CREATE TABLE audit_logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor TEXT NOT NULL,
  actor_kind TEXT NOT NULL,
  token_id INTEGER,
  command TEXT NOT NULL,
  args_digest TEXT NOT NULL,
  full_command TEXT,
  output TEXT,
  plan_id INTEGER,
  result TEXT NOT NULL
);

--bun:split

CREATE TABLE automation_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  trigger TEXT NOT NULL,
  condition TEXT NOT NULL DEFAULT '{}',
  action TEXT NOT NULL CHECK (action IN ('disable_user', 'disconnect', 'throttle', 'detach_node', 'notify', 'write_task')),
  max_targets INTEGER,
  deadline_minutes INTEGER,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  proposed_by TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved')),
  approved_by TEXT,
  approved_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT
);

--bun:split

CREATE UNIQUE INDEX automation_rules_name_key ON automation_rules (name);

--bun:split

CREATE TABLE batch_op_counters (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token_id INTEGER,
  actor TEXT NOT NULL,
  at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  objects INTEGER NOT NULL,
  command TEXT NOT NULL
);

--bun:split

CREATE TABLE config_snapshots (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  object_kind TEXT NOT NULL,
  object_id INTEGER NOT NULL,
  object_version INTEGER NOT NULL,
  content TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  apply_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE TABLE evidence_packages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  server_id INTEGER,
  collected_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  items TEXT NOT NULL DEFAULT '{}',
  collect_error TEXT,
  size_bytes INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE TABLE alerts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  category TEXT NOT NULL,
  level TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  object_id TEXT NOT NULL,
  dedup_key TEXT NOT NULL CHECK (dedup_key <> ''),
  conditions TEXT NOT NULL DEFAULT '[]',
  evidence_id INTEGER,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'recovered', 'resolved')),
  resolve_reason TEXT,
  occurrence_count INTEGER NOT NULL DEFAULT 1,
  first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT,
  FOREIGN KEY (evidence_id) REFERENCES evidence_packages (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX alerts_dedup_key_active ON alerts (dedup_key) WHERE status <> 'resolved';

--bun:split

CREATE TABLE jobs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  job_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  server_id INTEGER,
  args TEXT NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed', 'unknown')),
  started_at TEXT,
  finished_at TEXT,
  exit_code INTEGER,
  output TEXT,
  output_truncated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT
);

--bun:split

CREATE UNIQUE INDEX jobs_job_id_key ON jobs (job_id);

--bun:split

CREATE TABLE notify_channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('telegram', 'webhook')),
  events TEXT NOT NULL DEFAULT '[]',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  target TEXT NOT NULL DEFAULT '',
  secret TEXT NOT NULL DEFAULT '',
  last_delivered_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT
);

--bun:split

CREATE UNIQUE INDEX notify_channels_name_key ON notify_channels (name);

--bun:split

CREATE TABLE notify_deliveries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  delivery_id TEXT NOT NULL,
  channel_id INTEGER NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('alerts', 'tasks')),
  payload TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'void')),
  last_error TEXT,
  last_attempt_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (channel_id) REFERENCES notify_channels (id)
);

--bun:split

CREATE UNIQUE INDEX notify_deliveries_delivery_id_key ON notify_deliveries (delivery_id);

--bun:split

CREATE TABLE alert_deliveries (
  alert_id INTEGER NOT NULL,
  delivery_id INTEGER NOT NULL,
  PRIMARY KEY (alert_id, delivery_id),
  FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE CASCADE,
  FOREIGN KEY (delivery_id) REFERENCES notify_deliveries (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  objects TEXT NOT NULL,
  diff TEXT NOT NULL,
  affected_count INTEGER NOT NULL,
  share_identity TEXT,
  share_scope TEXT,
  expires_at TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'expired', 'rejected')),
  apply_id TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT
);

--bun:split

CREATE TABLE tasks (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT,
  source TEXT NOT NULL CHECK (source IN ('system', 'admin')),
  dedup_key TEXT NOT NULL DEFAULT '',
  alert_id INTEGER,
  evidence_id INTEGER,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'done', 'cancelled')),
  claimed_by INTEGER,
  lease_until TEXT,
  cancel_reason TEXT,
  expires_at TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version INTEGER NOT NULL DEFAULT 1,
  deleted_at TEXT,
  FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE SET NULL,
  FOREIGN KEY (evidence_id) REFERENCES evidence_packages (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX tasks_dedup_key_active ON tasks (dedup_key) WHERE status IN ('open', 'claimed') AND dedup_key <> '';
