-- Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.
-- 方言：postgres。表结构的唯一来源是 internal/base/schema 的注册表，改表先改注册表再重新生成。

CREATE TABLE audit_logs (
  id BIGSERIAL PRIMARY KEY,
  at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actor TEXT NOT NULL,
  actor_kind TEXT NOT NULL,
  token_id BIGINT,
  command TEXT NOT NULL,
  args_digest TEXT NOT NULL,
  full_command TEXT,
  output TEXT,
  plan_id BIGINT,
  result TEXT NOT NULL
);

--bun:split

CREATE TABLE automation_rules (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  trigger TEXT NOT NULL,
  condition JSONB NOT NULL DEFAULT '{}',
  action TEXT NOT NULL CHECK (action IN ('disable_user', 'disconnect', 'throttle', 'detach_node', 'notify', 'write_task')),
  max_targets BIGINT,
  deadline_minutes BIGINT,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  proposed_by TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved')),
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX automation_rules_name_key ON automation_rules (name);

--bun:split

CREATE TABLE batch_op_counters (
  id BIGSERIAL PRIMARY KEY,
  token_id BIGINT,
  actor TEXT NOT NULL,
  at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  objects BIGINT NOT NULL,
  command TEXT NOT NULL
);

--bun:split

CREATE TABLE config_snapshots (
  id BIGSERIAL PRIMARY KEY,
  object_kind TEXT NOT NULL,
  object_id BIGINT NOT NULL,
  object_version BIGINT NOT NULL,
  content JSONB NOT NULL,
  content_hash TEXT NOT NULL,
  source TEXT NOT NULL,
  status TEXT NOT NULL,
  apply_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE TABLE custom_rules (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('dns', 'rules', 'rule-providers')),
  mode TEXT NOT NULL CHECK (mode IN ('replace', 'prepend', 'append')),
  content TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX custom_rules_name_type_key ON custom_rules (name, type);

--bun:split

CREATE INDEX custom_rules_type_idx ON custom_rules (type);

--bun:split

CREATE INDEX custom_rules_enabled_idx ON custom_rules (enabled);

--bun:split

CREATE TABLE dns_providers (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  provider_type TEXT NOT NULL,
  credentials JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX dns_providers_name_key ON dns_providers (name);

--bun:split

CREATE TABLE invite_code_uses (
  code TEXT NOT NULL,
  username TEXT NOT NULL,
  tg_id BIGINT,
  used_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (code, username)
);

--bun:split

CREATE INDEX invite_code_uses_username_idx ON invite_code_uses (username);

--bun:split

CREATE TABLE invite_codes (
  code TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('new', 'bind')),
  bind_username TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL,
  package_id BIGINT,
  max_uses BIGINT NOT NULL DEFAULT 1,
  used_count BIGINT NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  remark TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  duration_months BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (code)
);

--bun:split

CREATE INDEX invite_codes_created_by_idx ON invite_codes (created_by);

--bun:split

CREATE INDEX invite_codes_kind_idx ON invite_codes (kind);

--bun:split

CREATE TABLE ip_bans (
  ip TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  banned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMPTZ,
  permanent BOOLEAN NOT NULL DEFAULT FALSE,
  fail_count BIGINT NOT NULL DEFAULT 0,
  released_at TIMESTAMPTZ,
  actor TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (ip)
);

--bun:split

CREATE INDEX ip_bans_active_idx ON ip_bans (released_at, expires_at);

--bun:split

CREATE TABLE node_traffic_snapshots (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'inbound',
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX node_traffic_snapshots_server_tag_type_date_key ON node_traffic_snapshots (server_id, tag, type, date);

--bun:split

CREATE INDEX node_traffic_snapshots_date_idx ON node_traffic_snapshots (date);

--bun:split

CREATE TABLE notify_channels (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('telegram', 'webhook')),
  events JSONB NOT NULL DEFAULT '[]',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  target TEXT NOT NULL DEFAULT '',
  secret TEXT NOT NULL DEFAULT '',
  last_delivered_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX notify_channels_name_key ON notify_channels (name);

--bun:split

CREATE TABLE notify_deliveries (
  id BIGSERIAL PRIMARY KEY,
  delivery_id TEXT NOT NULL,
  channel_id BIGINT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('alerts', 'tasks')),
  payload JSONB NOT NULL,
  attempts BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'sent', 'failed', 'void')),
  last_error TEXT,
  last_attempt_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (channel_id) REFERENCES notify_channels (id)
);

--bun:split

CREATE UNIQUE INDEX notify_deliveries_delivery_id_key ON notify_deliveries (delivery_id);

--bun:split

CREATE TABLE package_node_traffic_suspensions (
  username TEXT NOT NULL,
  package_id BIGINT NOT NULL,
  node_id BIGINT NOT NULL,
  kind TEXT NOT NULL,
  credential_json JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, package_id, node_id, kind)
);

--bun:split

CREATE TABLE package_user_node_traffic_baselines (
  username TEXT NOT NULL,
  package_id BIGINT NOT NULL,
  node_id BIGINT NOT NULL,
  baseline DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, package_id, node_id)
);

--bun:split

CREATE TABLE packages (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  traffic_limit_bytes BIGINT NOT NULL DEFAULT 0,
  cycle_days BIGINT NOT NULL DEFAULT 30,
  is_reset BOOLEAN NOT NULL DEFAULT FALSE,
  reset_day BIGINT NOT NULL DEFAULT 1,
  nodes JSONB NOT NULL DEFAULT '[]',
  device_limit BIGINT NOT NULL DEFAULT 0,
  speed_limit_mbps DOUBLE PRECISION NOT NULL DEFAULT 0,
  auto_speed_limit_json JSONB NOT NULL DEFAULT '[]',
  traffic_mode TEXT NOT NULL DEFAULT 'oneway' CHECK (traffic_mode IN ('oneway', 'twoway')),
  template_filename TEXT NOT NULL DEFAULT '',
  surge_template_filename TEXT NOT NULL DEFAULT '',
  short_code TEXT NOT NULL DEFAULT '',
  node_multipliers JSONB NOT NULL DEFAULT '{}',
  node_traffic_limits JSONB NOT NULL DEFAULT '{}',
  node_speed_limits JSONB NOT NULL DEFAULT '{}',
  node_device_limits JSONB NOT NULL DEFAULT '{}',
  node_name_overrides JSONB NOT NULL DEFAULT '{}',
  node_name_override_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX packages_name_key ON packages (name);

--bun:split

CREATE TABLE plans (
  id BIGSERIAL PRIMARY KEY,
  objects JSONB NOT NULL,
  diff JSONB NOT NULL,
  affected_count BIGINT NOT NULL,
  share_identity TEXT,
  share_scope JSONB,
  expires_at TIMESTAMPTZ NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'applied', 'expired', 'rejected')),
  apply_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE TABLE rule_template_owners (
  filename TEXT NOT NULL,
  created_by TEXT NOT NULL DEFAULT '',
  PRIMARY KEY (filename)
);

--bun:split

CREATE TABLE rule_versions (
  id BIGSERIAL PRIMARY KEY,
  filename TEXT NOT NULL,
  version BIGINT NOT NULL,
  content TEXT NOT NULL,
  created_by TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX rule_versions_filename_version_key ON rule_versions (filename, version);

--bun:split

CREATE TABLE security_events (
  id BIGSERIAL PRIMARY KEY,
  at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ip TEXT NOT NULL,
  kind TEXT NOT NULL,
  path TEXT NOT NULL DEFAULT '',
  username TEXT NOT NULL DEFAULT '',
  detail TEXT NOT NULL DEFAULT '',
  actor TEXT NOT NULL DEFAULT ''
);

--bun:split

CREATE INDEX security_events_at_idx ON security_events (at);

--bun:split

CREATE INDEX security_events_ip_idx ON security_events (ip);

--bun:split

CREATE INDEX security_events_kind_at_idx ON security_events (kind, at);

--bun:split

CREATE TABLE server_system_traffic_snapshots (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  rx_cycle BIGINT NOT NULL DEFAULT 0,
  tx_cycle BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX server_system_traffic_snapshots_server_date_key ON server_system_traffic_snapshots (server_id, date);

--bun:split

CREATE INDEX server_system_traffic_snapshots_date_idx ON server_system_traffic_snapshots (date);

--bun:split

CREATE TABLE servers (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  ipv6_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  domain TEXT NOT NULL DEFAULT '',
  domain_v6 TEXT NOT NULL DEFAULT '',
  connection_mode TEXT NOT NULL DEFAULT 'auto' CHECK (connection_mode IN ('auto', 'websocket', 'http', 'pull')),
  pull_address TEXT NOT NULL DEFAULT '',
  pull_address_v6 TEXT NOT NULL DEFAULT '',
  pull_port BIGINT NOT NULL DEFAULT 0,
  listen_port BIGINT NOT NULL DEFAULT 0,
  lock_entry_ip BOOLEAN NOT NULL DEFAULT FALSE,
  use_443 BOOLEAN NOT NULL DEFAULT FALSE,
  steal_mode TEXT NOT NULL DEFAULT 'tunnel' CHECK (steal_mode IN ('tunnel', 'fallback')),
  site_type TEXT NOT NULL DEFAULT '',
  site_value TEXT NOT NULL DEFAULT '',
  port_range_min BIGINT NOT NULL DEFAULT 0,
  port_range_max BIGINT NOT NULL DEFAULT 0,
  traffic_limit BIGINT NOT NULL DEFAULT 0,
  traffic_reset_day BIGINT NOT NULL DEFAULT 0,
  traffic_stats_mode TEXT NOT NULL DEFAULT 'both' CHECK (traffic_stats_mode IN ('both', 'upload', 'download', 'max')),
  traffic_source TEXT NOT NULL DEFAULT 'core' CHECK (traffic_source IN ('core', 'system')),
  include_in_traffic_stats BOOLEAN NOT NULL DEFAULT FALSE,
  traffic_calibration BIGINT NOT NULL DEFAULT 0,
  region TEXT NOT NULL DEFAULT '',
  region_country TEXT NOT NULL DEFAULT '',
  region_name TEXT NOT NULL DEFAULT '',
  region_city TEXT NOT NULL DEFAULT '',
  renewal_price DOUBLE PRECISION NOT NULL DEFAULT 0,
  renewal_cycle TEXT NOT NULL DEFAULT 'month',
  renewal_currency TEXT NOT NULL DEFAULT 'CNY',
  provider_name TEXT NOT NULL DEFAULT '',
  provider_url TEXT NOT NULL DEFAULT '',
  telecom_paid_peer BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ,
  ddns_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  ddns_provider_id BIGINT,
  ddns_record_name TEXT NOT NULL DEFAULT '',
  core_log_level TEXT NOT NULL DEFAULT 'warn',
  core_dns JSONB NOT NULL DEFAULT '{}',
  core_stats_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order BIGINT NOT NULL DEFAULT 0,
  token TEXT NOT NULL,
  agent_token TEXT NOT NULL DEFAULT '',
  pull_token TEXT NOT NULL DEFAULT '',
  token_expires_at TIMESTAMPTZ,
  agent_token_expires_at TIMESTAMPTZ,
  last_token_refresh TIMESTAMPTZ,
  last_agent_token_refresh TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'connected', 'offline')),
  last_heartbeat TIMESTAMPTZ,
  ip_address TEXT,
  ip_address_v6 TEXT NOT NULL DEFAULT '',
  boot_time TIMESTAMPTZ,
  boot_count BIGINT NOT NULL DEFAULT 0,
  core_boot_time TIMESTAMPTZ,
  core_boot_count BIGINT NOT NULL DEFAULT 0,
  core_running BOOLEAN NOT NULL DEFAULT FALSE,
  core_version TEXT NOT NULL DEFAULT '',
  current_upload_speed BIGINT NOT NULL DEFAULT 0,
  current_download_speed BIGINT NOT NULL DEFAULT 0,
  speed_updated_at TIMESTAMPTZ,
  offline_since TIMESTAMPTZ,
  offline_notified BOOLEAN NOT NULL DEFAULT FALSE,
  warp_installed BOOLEAN NOT NULL DEFAULT FALSE,
  same_host_as_master BOOLEAN NOT NULL DEFAULT FALSE,
  time_offset_seconds BIGINT,
  push_fail_count BIGINT NOT NULL DEFAULT 0,
  last_push_fail TIMESTAMPTZ,
  fallback_to_pull BOOLEAN NOT NULL DEFAULT FALSE,
  fallback_at TIMESTAMPTZ,
  last_pull_at TIMESTAMPTZ,
  system_rx_cycle BIGINT NOT NULL DEFAULT 0,
  system_tx_cycle BIGINT NOT NULL DEFAULT 0,
  system_last_seen_rx BIGINT NOT NULL DEFAULT 0,
  system_last_seen_tx BIGINT NOT NULL DEFAULT 0,
  system_boot_time_unix BIGINT NOT NULL DEFAULT 0,
  system_traffic_updated_at TIMESTAMPTZ,
  traffic_reset_baseline BIGINT NOT NULL DEFAULT 0,
  last_traffic_reset_at TIMESTAMPTZ,
  ddns_last_synced_at TIMESTAMPTZ,
  ddns_last_error TEXT NOT NULL DEFAULT '',
  ddns_pending BOOLEAN NOT NULL DEFAULT FALSE,
  provider_updated_at TIMESTAMPTZ,
  rotation_pending BOOLEAN NOT NULL DEFAULT FALSE,
  last_rotated_at TIMESTAMPTZ,
  revoke_pending BOOLEAN NOT NULL DEFAULT FALSE,
  applied_hash TEXT NOT NULL DEFAULT '',
  applied_generation BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (ddns_provider_id) REFERENCES dns_providers (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX servers_name_key ON servers (name);

--bun:split

CREATE UNIQUE INDEX servers_token_key ON servers (token);

--bun:split

CREATE INDEX servers_status_idx ON servers (status);

--bun:split

CREATE TABLE batch_inbounds (
  id BIGSERIAL PRIMARY KEY,
  batch_id TEXT NOT NULL,
  tag TEXT NOT NULL,
  server_id BIGINT NOT NULL,
  protocol TEXT NOT NULL,
  port BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX batch_inbounds_batch_idx ON batch_inbounds (batch_id);

--bun:split

CREATE INDEX batch_inbounds_server_idx ON batch_inbounds (server_id);

--bun:split

CREATE INDEX batch_inbounds_tag_idx ON batch_inbounds (tag);

--bun:split

CREATE TABLE batch_outbounds (
  id BIGSERIAL PRIMARY KEY,
  batch_id TEXT NOT NULL,
  tag TEXT NOT NULL,
  server_id BIGINT NOT NULL,
  protocol TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX batch_outbounds_batch_idx ON batch_outbounds (batch_id);

--bun:split

CREATE INDEX batch_outbounds_server_idx ON batch_outbounds (server_id);

--bun:split

CREATE INDEX batch_outbounds_tag_idx ON batch_outbounds (tag);

--bun:split

CREATE TABLE certificates (
  id BIGSERIAL PRIMARY KEY,
  domain TEXT NOT NULL,
  email TEXT NOT NULL,
  provider TEXT NOT NULL DEFAULT 'letsencrypt',
  challenge_mode TEXT NOT NULL DEFAULT 'standalone' CHECK (challenge_mode IN ('standalone', 'webroot', 'dns', 'manual')),
  webroot_path TEXT,
  server_id BIGINT,
  dns_provider_id BIGINT,
  cert_pem TEXT,
  key_pem TEXT,
  auto_renew BOOLEAN NOT NULL DEFAULT FALSE,
  deploy_target TEXT NOT NULL DEFAULT 'none',
  deploy_cert_path TEXT,
  deploy_key_path TEXT,
  auto_deploy BOOLEAN NOT NULL DEFAULT FALSE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'valid', 'expired', 'failed')),
  expiry_date TIMESTAMPTZ,
  issue_date TIMESTAMPTZ,
  message TEXT,
  cert_path TEXT,
  key_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE RESTRICT,
  FOREIGN KEY (dns_provider_id) REFERENCES dns_providers (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX certificates_domain_server_key ON certificates (domain, server_id) WHERE server_id IS NOT NULL;

--bun:split

CREATE UNIQUE INDEX certificates_domain_local_key ON certificates (domain) WHERE server_id IS NULL;

--bun:split

CREATE INDEX certificates_domain_idx ON certificates (domain);

--bun:split

CREATE INDEX certificates_status_idx ON certificates (status);

--bun:split

CREATE INDEX certificates_server_id_idx ON certificates (server_id);

--bun:split

CREATE INDEX certificates_expiry_date_idx ON certificates (expiry_date);

--bun:split

CREATE TABLE evidence_packages (
  id BIGSERIAL PRIMARY KEY,
  category TEXT NOT NULL,
  server_id BIGINT,
  collected_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  items JSONB NOT NULL DEFAULT '{}',
  collect_error TEXT,
  size_bytes BIGINT NOT NULL DEFAULT 0,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE SET NULL
);

--bun:split

CREATE TABLE alerts (
  id BIGSERIAL PRIMARY KEY,
  category TEXT NOT NULL,
  level TEXT NOT NULL,
  object_kind TEXT NOT NULL,
  object_id TEXT NOT NULL,
  dedup_key TEXT NOT NULL CHECK (dedup_key <> ''),
  conditions JSONB NOT NULL DEFAULT '[]',
  evidence_id BIGINT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'recovered', 'resolved')),
  resolve_reason TEXT,
  occurrence_count BIGINT NOT NULL DEFAULT 1,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (evidence_id) REFERENCES evidence_packages (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX alerts_dedup_key_active ON alerts (dedup_key) WHERE status <> 'resolved';

--bun:split

CREATE TABLE alert_deliveries (
  alert_id BIGINT NOT NULL,
  delivery_id BIGINT NOT NULL,
  PRIMARY KEY (alert_id, delivery_id),
  FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE CASCADE,
  FOREIGN KEY (delivery_id) REFERENCES notify_deliveries (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE federated_servers (
  server_id BIGINT NOT NULL,
  owner_url TEXT NOT NULL,
  share_token TEXT NOT NULL,
  prefix TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE inbounds (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  protocol TEXT NOT NULL,
  port BIGINT NOT NULL,
  listen TEXT NOT NULL DEFAULT '',
  tls JSONB NOT NULL DEFAULT '{}',
  transport JSONB NOT NULL DEFAULT '{}',
  settings JSONB NOT NULL DEFAULT '{}',
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX inbounds_server_tag_key ON inbounds (server_id, tag);

--bun:split

CREATE TABLE jobs (
  id BIGSERIAL PRIMARY KEY,
  job_id TEXT NOT NULL,
  kind TEXT NOT NULL,
  server_id BIGINT,
  args JSONB NOT NULL DEFAULT '{}',
  status TEXT NOT NULL DEFAULT 'queued' CHECK (status IN ('queued', 'running', 'done', 'failed', 'unknown')),
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  exit_code BIGINT,
  output TEXT,
  output_truncated BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX jobs_job_id_key ON jobs (job_id);

--bun:split

CREATE TABLE node_traffic (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('inbound', 'outbound')),
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  total_uplink BIGINT NOT NULL DEFAULT 0,
  total_downlink BIGINT NOT NULL DEFAULT 0,
  last_uplink BIGINT NOT NULL DEFAULT 0,
  last_downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX node_traffic_server_tag_type_key ON node_traffic (server_id, tag, type);

--bun:split

CREATE INDEX node_traffic_server_id_idx ON node_traffic (server_id);

--bun:split

CREATE INDEX node_traffic_tag_idx ON node_traffic (tag);

--bun:split

CREATE INDEX node_traffic_type_idx ON node_traffic (type);

--bun:split

CREATE TABLE outbounds (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  protocol TEXT NOT NULL,
  settings JSONB NOT NULL DEFAULT '{}',
  is_warp BOOLEAN NOT NULL DEFAULT FALSE,
  balancer_group TEXT NOT NULL DEFAULT '',
  probe JSONB NOT NULL DEFAULT '{}',
  last_probe_ok BOOLEAN NOT NULL DEFAULT FALSE,
  last_probe_latency_ms BIGINT,
  last_probed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX outbounds_server_tag_key ON outbounds (server_id, tag);

--bun:split

CREATE TABLE return_routes (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  carrier TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  probe JSONB NOT NULL DEFAULT '{}',
  route_type TEXT NOT NULL DEFAULT 'Unknown',
  region TEXT NOT NULL DEFAULT '',
  entry_ip TEXT NOT NULL DEFAULT '',
  entry_asn TEXT NOT NULL DEFAULT '',
  reason TEXT NOT NULL DEFAULT '',
  tested_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX return_routes_server_carrier_key ON return_routes (server_id, carrier);

--bun:split

CREATE INDEX return_routes_tested_at_idx ON return_routes (tested_at);

--bun:split

CREATE TABLE routing_rules (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  sort_order BIGINT NOT NULL DEFAULT 0,
  match JSONB NOT NULL DEFAULT '{}',
  outbound_tag TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  catch_all BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX routing_rules_server_order_idx ON routing_rules (server_id, sort_order);

--bun:split

CREATE TABLE shared_servers (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  token_hash TEXT NOT NULL,
  label TEXT NOT NULL DEFAULT '',
  allow_manage_inbounds BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  revoked_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX shared_servers_token_hash_key ON shared_servers (token_hash);

--bun:split

CREATE TABLE shared_server_inbounds (
  share_id BIGINT NOT NULL,
  server_id BIGINT NOT NULL,
  inbound_tag TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (share_id, inbound_tag),
  FOREIGN KEY (share_id) REFERENCES shared_servers (id) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE speed_test_results (
  id BIGSERIAL PRIMARY KEY,
  node_id BIGINT NOT NULL,
  node_name TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'master_local',
  down_mbps DOUBLE PRECISION NOT NULL DEFAULT 0,
  latency_ms BIGINT NOT NULL DEFAULT -1,
  test_bytes BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'ok',
  error TEXT NOT NULL DEFAULT '',
  tested_by TEXT NOT NULL DEFAULT '',
  egress_ip TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE INDEX speed_test_results_node_idx ON speed_test_results (node_id);

--bun:split

CREATE TABLE speed_testers (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT '',
  token_hash TEXT NOT NULL,
  created_by TEXT NOT NULL DEFAULT '',
  last_seen TIMESTAMPTZ,
  caps TEXT NOT NULL DEFAULT '',
  version TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX speed_testers_token_hash_key ON speed_testers (token_hash);

--bun:split

CREATE TABLE subscribe_files (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  url TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('create', 'import', 'upload', 'package')),
  filename TEXT NOT NULL,
  expire_at TIMESTAMPTZ,
  file_short_code TEXT NOT NULL DEFAULT '',
  custom_short_code TEXT NOT NULL DEFAULT '',
  auto_sync_custom_rules BOOLEAN NOT NULL DEFAULT FALSE,
  template_filename TEXT NOT NULL DEFAULT '',
  selected_custom_rule_ids JSONB NOT NULL DEFAULT '[]',
  selected_override_script_ids JSONB NOT NULL DEFAULT '[]',
  selected_tags JSONB NOT NULL DEFAULT '[]',
  selected_node_ids JSONB NOT NULL DEFAULT '[]',
  stats_server_ids TEXT NOT NULL DEFAULT '',
  traffic_limit DOUBLE PRECISION,
  sort_order BIGINT NOT NULL DEFAULT 0,
  raw_output BOOLEAN NOT NULL DEFAULT FALSE,
  created_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX subscribe_files_name_key ON subscribe_files (name);

--bun:split

CREATE INDEX subscribe_files_type_idx ON subscribe_files (type);

--bun:split

CREATE UNIQUE INDEX subscribe_files_file_short_code_key ON subscribe_files (file_short_code) WHERE file_short_code <> '';

--bun:split

CREATE UNIQUE INDEX subscribe_files_custom_short_code_key ON subscribe_files (custom_short_code) WHERE custom_short_code <> '';

--bun:split

CREATE TABLE custom_rule_applications (
  id BIGSERIAL PRIMARY KEY,
  subscribe_file_id BIGINT NOT NULL,
  custom_rule_id BIGINT NOT NULL,
  rule_type TEXT NOT NULL,
  rule_mode TEXT NOT NULL,
  applied_content TEXT NOT NULL,
  content_hash TEXT NOT NULL,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (subscribe_file_id) REFERENCES subscribe_files (id) ON DELETE CASCADE,
  FOREIGN KEY (custom_rule_id) REFERENCES custom_rules (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX custom_rule_applications_file_rule_type_key ON custom_rule_applications (subscribe_file_id, custom_rule_id, rule_type);

--bun:split

CREATE INDEX custom_rule_applications_file_idx ON custom_rule_applications (subscribe_file_id);

--bun:split

CREATE INDEX custom_rule_applications_rule_idx ON custom_rule_applications (custom_rule_id);

--bun:split

CREATE TABLE subscription_links (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT '',
  description TEXT,
  rule_filename TEXT NOT NULL,
  buttons JSONB NOT NULL DEFAULT '[]',
  short_url TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX subscription_links_name_key ON subscription_links (name);

--bun:split

CREATE UNIQUE INDEX subscription_links_short_url_key ON subscription_links (short_url) WHERE short_url <> '';

--bun:split

CREATE TABLE system_config (
  id BIGINT NOT NULL DEFAULT 1 CHECK (id = 1),
  proxy_groups_source_url TEXT NOT NULL DEFAULT '',
  client_compatibility_mode BOOLEAN NOT NULL DEFAULT FALSE,
  enable_short_link BOOLEAN NOT NULL DEFAULT FALSE,
  enable_sub_info_nodes BOOLEAN NOT NULL DEFAULT FALSE,
  sub_info_v2ray_only BOOLEAN NOT NULL DEFAULT FALSE,
  sub_info_expire_prefix TEXT NOT NULL DEFAULT '📅过期时间',
  sub_info_traffic_prefix TEXT NOT NULL DEFAULT '⌛剩余流量',
  speed_collect_interval BIGINT NOT NULL DEFAULT 3,
  traffic_collect_interval BIGINT NOT NULL DEFAULT 60,
  traffic_check_interval BIGINT NOT NULL DEFAULT 120,
  heartbeat_interval BIGINT NOT NULL DEFAULT 30,
  agent_log_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  notify_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  telegram_bot_token TEXT NOT NULL DEFAULT '',
  telegram_chat_id TEXT NOT NULL DEFAULT '',
  notify_login BOOLEAN NOT NULL DEFAULT FALSE,
  notify_subscribe_fetch BOOLEAN NOT NULL DEFAULT FALSE,
  notify_daily_traffic BOOLEAN NOT NULL DEFAULT FALSE,
  notify_server_offline BOOLEAN NOT NULL DEFAULT FALSE,
  notify_server_online BOOLEAN NOT NULL DEFAULT FALSE,
  notify_traffic_threshold BOOLEAN NOT NULL DEFAULT FALSE,
  notify_daily_traffic_time TEXT NOT NULL DEFAULT '08:00',
  notify_traffic_threshold_percent BIGINT NOT NULL DEFAULT 80,
  notify_traffic_threshold_80 BOOLEAN NOT NULL DEFAULT FALSE,
  notify_over_limit BOOLEAN NOT NULL DEFAULT FALSE,
  notify_package_expiring BOOLEAN NOT NULL DEFAULT FALSE,
  notify_package_expiring_days BIGINT NOT NULL DEFAULT 3,
  notify_package_expired BOOLEAN NOT NULL DEFAULT FALSE,
  notify_user_registered BOOLEAN NOT NULL DEFAULT FALSE,
  notify_telegram_bound BOOLEAN NOT NULL DEFAULT FALSE,
  notify_cert_result BOOLEAN NOT NULL DEFAULT FALSE,
  notify_agent_long_offline BOOLEAN NOT NULL DEFAULT FALSE,
  notify_agent_long_offline_minutes BIGINT NOT NULL DEFAULT 30,
  notify_device_limit_exceeded BOOLEAN NOT NULL DEFAULT FALSE,
  notify_server_renewal BOOLEAN NOT NULL DEFAULT FALSE,
  notify_ip_ban BOOLEAN NOT NULL DEFAULT FALSE,
  enable_override_scripts BOOLEAN NOT NULL DEFAULT FALSE,
  subscription_output_format TEXT NOT NULL DEFAULT 'yaml',
  silent_mode BOOLEAN NOT NULL DEFAULT FALSE,
  silent_mode_timeout BIGINT NOT NULL DEFAULT 15,
  enable_miaomiaowu_features BOOLEAN NOT NULL DEFAULT FALSE,
  default_template_filename TEXT NOT NULL DEFAULT '',
  default_surge_template_filename TEXT NOT NULL DEFAULT '',
  node_name_multiplier_prefix_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  node_name_multiplier_left TEXT NOT NULL DEFAULT '「',
  node_name_multiplier_right TEXT NOT NULL DEFAULT '」',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  PRIMARY KEY (id)
);

--bun:split

CREATE TABLE system_settings (
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key)
);

--bun:split

CREATE TABLE task_runs (
  id BIGSERIAL PRIMARY KEY,
  task_name TEXT NOT NULL,
  started_at TIMESTAMPTZ NOT NULL,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  status TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT ''
);

--bun:split

CREATE INDEX task_runs_name_started_idx ON task_runs (task_name, started_at);

--bun:split

CREATE INDEX task_runs_started_idx ON task_runs (started_at);

--bun:split

CREATE TABLE templates (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'clash' CHECK (category IN ('clash', 'surge')),
  template_url TEXT NOT NULL DEFAULT '',
  rule_source TEXT NOT NULL DEFAULT '',
  use_proxy BOOLEAN NOT NULL DEFAULT FALSE,
  enable_include_all BOOLEAN NOT NULL DEFAULT FALSE,
  created_by TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX templates_name_key ON templates (name);

--bun:split

CREATE INDEX templates_category_idx ON templates (category);

--bun:split

CREATE TABLE tg_audit (
  id BIGSERIAL PRIMARY KEY,
  tg_id BIGINT,
  username TEXT NOT NULL DEFAULT '',
  action TEXT NOT NULL,
  detail TEXT NOT NULL DEFAULT '',
  at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE INDEX tg_audit_tg_id_idx ON tg_audit (tg_id);

--bun:split

CREATE INDEX tg_audit_username_idx ON tg_audit (username);

--bun:split

CREATE INDEX tg_audit_at_idx ON tg_audit (at);

--bun:split

CREATE TABLE traffic_daily_incomplete_dates (
  date TEXT NOT NULL,
  reason TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (date)
);

--bun:split

CREATE TABLE traffic_daily_meta (
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (key)
);

--bun:split

CREATE TABLE traffic_daily_nodes (
  server_id BIGINT NOT NULL,
  tag TEXT NOT NULL,
  type TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, tag, type, date),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_nodes_date_idx ON traffic_daily_nodes (date);

--bun:split

CREATE TABLE traffic_daily_system_servers (
  server_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, date),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_system_servers_date_idx ON traffic_daily_system_servers (date);

--bun:split

CREATE TABLE traffic_daily_user_emails (
  server_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  attributed_username TEXT NOT NULL DEFAULT '',
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  weighted_uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  weighted_downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, email, attributed_username, date),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_user_emails_date_idx ON traffic_daily_user_emails (date);

--bun:split

CREATE INDEX traffic_daily_user_emails_user_idx ON traffic_daily_user_emails (attributed_username);

--bun:split

CREATE TABLE traffic_daily_user_nodes (
  server_id BIGINT NOT NULL,
  node_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  weighted_uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  weighted_downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, node_id, username, date),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_user_nodes_date_idx ON traffic_daily_user_nodes (date);

--bun:split

CREATE INDEX traffic_daily_user_nodes_user_idx ON traffic_daily_user_nodes (username);

--bun:split

CREATE INDEX traffic_daily_user_nodes_node_idx ON traffic_daily_user_nodes (node_id);

--bun:split

CREATE TABLE traffic_daily_users (
  server_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id, username, date),
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_users_date_idx ON traffic_daily_users (date);

--bun:split

CREATE TABLE traffic_daily_users_archived (
  username TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, date)
);

--bun:split

CREATE INDEX traffic_daily_users_archived_date_idx ON traffic_daily_users_archived (date);

--bun:split

CREATE TABLE traffic_records (
  date TEXT NOT NULL,
  total_limit BIGINT NOT NULL,
  total_used BIGINT NOT NULL,
  total_remaining BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (date)
);

--bun:split

CREATE TABLE traffic_snapshots (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  inbound_uplink BIGINT NOT NULL DEFAULT 0,
  inbound_downlink BIGINT NOT NULL DEFAULT 0,
  outbound_uplink BIGINT NOT NULL DEFAULT 0,
  outbound_downlink BIGINT NOT NULL DEFAULT 0,
  user_uplink BIGINT NOT NULL DEFAULT 0,
  user_downlink BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX traffic_snapshots_server_date_key ON traffic_snapshots (server_id, date);

--bun:split

CREATE INDEX traffic_snapshots_server_id_idx ON traffic_snapshots (server_id);

--bun:split

CREATE INDEX traffic_snapshots_date_idx ON traffic_snapshots (date);

--bun:split

CREATE TABLE traffic_threshold_notified (
  server_id BIGINT NOT NULL,
  notified_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (server_id)
);

--bun:split

CREATE TABLE user_email_traffic (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  total_uplink BIGINT NOT NULL DEFAULT 0,
  total_downlink BIGINT NOT NULL DEFAULT 0,
  last_uplink BIGINT NOT NULL DEFAULT 0,
  last_downlink BIGINT NOT NULL DEFAULT 0,
  cycle_base_uplink BIGINT NOT NULL DEFAULT 0,
  cycle_base_downlink BIGINT NOT NULL DEFAULT 0,
  weighted_uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  weighted_downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  cycle_base_weighted_uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  cycle_base_weighted_downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  attributed_username TEXT NOT NULL DEFAULT '',
  cycle_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX user_email_traffic_server_email_key ON user_email_traffic (server_id, email);

--bun:split

CREATE INDEX user_email_traffic_server_id_idx ON user_email_traffic (server_id);

--bun:split

CREATE INDEX user_email_traffic_email_idx ON user_email_traffic (email);

--bun:split

CREATE INDEX user_email_traffic_attributed_username_idx ON user_email_traffic (attributed_username);

--bun:split

CREATE TABLE user_email_traffic_snapshots (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX user_email_traffic_snapshots_server_email_date_key ON user_email_traffic_snapshots (server_id, email, date);

--bun:split

CREATE INDEX user_email_traffic_snapshots_date_idx ON user_email_traffic_snapshots (date);

--bun:split

CREATE TABLE user_routed_outbound_actions (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  action TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE INDEX user_routed_outbound_actions_user_idx ON user_routed_outbound_actions (username, created_at);

--bun:split

CREATE TABLE user_traffic (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  total_uplink BIGINT NOT NULL DEFAULT 0,
  total_downlink BIGINT NOT NULL DEFAULT 0,
  last_uplink BIGINT NOT NULL DEFAULT 0,
  last_downlink BIGINT NOT NULL DEFAULT 0,
  cycle_start TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX user_traffic_server_username_key ON user_traffic (server_id, username);

--bun:split

CREATE INDEX user_traffic_server_id_idx ON user_traffic (server_id);

--bun:split

CREATE INDEX user_traffic_username_idx ON user_traffic (username);

--bun:split

CREATE TABLE user_traffic_cycle_carry (
  username TEXT NOT NULL,
  weighted_uplink DOUBLE PRECISION NOT NULL DEFAULT 0,
  weighted_downlink DOUBLE PRECISION NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username)
);

--bun:split

CREATE TABLE user_traffic_records (
  username TEXT NOT NULL,
  date TEXT NOT NULL,
  total_limit BIGINT NOT NULL,
  total_used BIGINT NOT NULL,
  total_remaining BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, date)
);

--bun:split

CREATE TABLE user_traffic_snapshots (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

--bun:split

CREATE UNIQUE INDEX user_traffic_snapshots_server_username_date_key ON user_traffic_snapshots (server_id, username, date);

--bun:split

CREATE INDEX user_traffic_snapshots_date_idx ON user_traffic_snapshots (date);

--bun:split

CREATE TABLE users (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  email TEXT,
  nickname TEXT,
  avatar_url TEXT,
  role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('admin', 'user')),
  remark TEXT,
  traffic_limit_override BIGINT,
  speed_limit_override DOUBLE PRECISION,
  device_limit_override BIGINT,
  node_speed_limit_overrides JSONB NOT NULL DEFAULT '{}',
  node_device_limit_overrides JSONB NOT NULL DEFAULT '{}',
  tg_notify_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  telegram_id BIGINT,
  telegram_username TEXT NOT NULL DEFAULT '',
  telegram_bound_at TIMESTAMPTZ,
  password_hash TEXT NOT NULL,
  totp_secret TEXT NOT NULL DEFAULT '',
  totp_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  recovery_codes JSONB NOT NULL DEFAULT '[]',
  is_over_limit BOOLEAN NOT NULL DEFAULT FALSE,
  over_limit_enforced BOOLEAN NOT NULL DEFAULT FALSE,
  disabled_access_enforced BOOLEAN NOT NULL DEFAULT FALSE,
  traffic_warned_80 BOOLEAN NOT NULL DEFAULT FALSE,
  last_reset_at TIMESTAMPTZ,
  last_package_id BIGINT,
  last_package_end_date TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ
);

--bun:split

CREATE UNIQUE INDEX users_username_key ON users (username);

--bun:split

CREATE INDEX users_email_idx ON users (email);

--bun:split

CREATE UNIQUE INDEX users_telegram_id_key ON users (telegram_id) WHERE telegram_id IS NOT NULL;

--bun:split

CREATE TABLE api_tokens (
  id BIGSERIAL PRIMARY KEY,
  owner TEXT NOT NULL,
  name TEXT NOT NULL DEFAULT '',
  token_hash TEXT NOT NULL,
  scopes JSONB NOT NULL DEFAULT '{}',
  preset TEXT NOT NULL DEFAULT 'readonly' CHECK (preset IN ('readonly', 'ops', 'full')),
  expires_at TIMESTAMPTZ,
  runtime TEXT,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  revoked_at TIMESTAMPTZ,
  last_used_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (owner) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX api_tokens_token_hash_key ON api_tokens (token_hash);

--bun:split

CREATE INDEX api_tokens_owner_idx ON api_tokens (owner);

--bun:split

CREATE TABLE external_subscriptions (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  user_agent TEXT NOT NULL DEFAULT 'clash-meta/2.4.0',
  traffic_mode TEXT NOT NULL DEFAULT 'both',
  node_count BIGINT NOT NULL DEFAULT 0,
  last_sync_at TIMESTAMPTZ,
  upload BIGINT NOT NULL DEFAULT 0,
  download BIGINT NOT NULL DEFAULT 0,
  total BIGINT NOT NULL DEFAULT 0,
  expire TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX external_subscriptions_username_url_key ON external_subscriptions (username, url);

--bun:split

CREATE INDEX external_subscriptions_username_idx ON external_subscriptions (username);

--bun:split

CREATE INDEX external_subscriptions_url_idx ON external_subscriptions (url);

--bun:split

CREATE TABLE nodes (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  server_id BIGINT,
  raw_url TEXT NOT NULL,
  node_name TEXT NOT NULL,
  protocol TEXT NOT NULL,
  parsed_config JSONB NOT NULL,
  clash_config TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  tag TEXT NOT NULL DEFAULT '手动输入',
  tags JSONB NOT NULL DEFAULT '[]',
  original_server TEXT,
  original_domain TEXT,
  inbound_tag TEXT,
  chain_proxy_node_id BIGINT,
  relay_group_name TEXT,
  relay_group_node_ids JSONB NOT NULL DEFAULT '[]',
  node_type TEXT NOT NULL DEFAULT 'physical',
  parent_node_id BIGINT,
  routed_outbound_tag TEXT,
  routed_outbound_json JSONB,
  routed_rule_marktag TEXT,
  routed_admin_email TEXT,
  routed_admin_credential TEXT,
  routed_owner TEXT NOT NULL DEFAULT 'shared',
  relay_orig_server TEXT,
  relay_orig_port BIGINT NOT NULL DEFAULT 0,
  ip_family TEXT NOT NULL DEFAULT '',
  detached BOOLEAN NOT NULL DEFAULT FALSE,
  detach_reason TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE SET NULL
);

--bun:split

CREATE INDEX nodes_username_idx ON nodes (username);

--bun:split

CREATE INDEX nodes_enabled_idx ON nodes (enabled);

--bun:split

CREATE INDEX nodes_parent_idx ON nodes (parent_node_id);

--bun:split

CREATE INDEX nodes_protocol_idx ON nodes (protocol);

--bun:split

CREATE INDEX nodes_tag_idx ON nodes (tag);

--bun:split

CREATE INDEX nodes_type_idx ON nodes (node_type);

--bun:split

CREATE TABLE announcements (
  id BIGSERIAL PRIMARY KEY,
  type TEXT NOT NULL DEFAULT 'general',
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  node_id BIGINT,
  via_bot BOOLEAN NOT NULL DEFAULT FALSE,
  via_miniapp BOOLEAN NOT NULL DEFAULT FALSE,
  expires_at TIMESTAMPTZ,
  bot_delivered_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE SET NULL
);

--bun:split

CREATE TABLE node_reachability (
  node_id BIGINT NOT NULL,
  reachable BOOLEAN NOT NULL DEFAULT FALSE,
  consecutive_fail BIGINT NOT NULL DEFAULT 0,
  since TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  announced_blocked BOOLEAN NOT NULL DEFAULT FALSE,
  PRIMARY KEY (node_id),
  FOREIGN KEY (node_id) REFERENCES nodes (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE override_scripts (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  name TEXT NOT NULL,
  hook TEXT NOT NULL,
  content TEXT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE INDEX override_scripts_username_idx ON override_scripts (username);

--bun:split

CREATE INDEX override_scripts_hook_idx ON override_scripts (hook);

--bun:split

CREATE TABLE package_assignments (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  package_id BIGINT NOT NULL,
  package_start_date TIMESTAMPTZ,
  package_end_date TIMESTAMPTZ,
  is_reset BOOLEAN NOT NULL DEFAULT FALSE,
  reset_day BIGINT NOT NULL DEFAULT 1,
  traffic_limit_override BIGINT,
  is_primary BOOLEAN NOT NULL DEFAULT FALSE,
  short_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  last_reset_at TIMESTAMPTZ,
  traffic_warned_80 BOOLEAN NOT NULL DEFAULT FALSE,
  over_limit_enforced BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (package_id) REFERENCES packages (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX package_assignments_short_code_key ON package_assignments (short_code);

--bun:split

CREATE INDEX package_assignments_user_status_idx ON package_assignments (username, status);

--bun:split

CREATE INDEX package_assignments_package_status_idx ON package_assignments (package_id, status);

--bun:split

CREATE TABLE package_assignment_inbound_configs (
  id BIGSERIAL PRIMARY KEY,
  assignment_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  server_id BIGINT NOT NULL,
  inbound_tag TEXT NOT NULL,
  protocol TEXT NOT NULL,
  email TEXT NOT NULL,
  credential_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assignment_id) REFERENCES package_assignments (id) ON DELETE CASCADE,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX package_assignment_inbound_configs_key ON package_assignment_inbound_configs (assignment_id, server_id, inbound_tag);

--bun:split

CREATE INDEX package_assignment_inbound_configs_server_idx ON package_assignment_inbound_configs (server_id);

--bun:split

CREATE INDEX package_assignment_inbound_configs_username_idx ON package_assignment_inbound_configs (username);

--bun:split

CREATE TABLE package_assignment_subaccounts (
  id BIGSERIAL PRIMARY KEY,
  assignment_id BIGINT NOT NULL,
  username TEXT NOT NULL,
  routed_node_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  credential_json JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (assignment_id) REFERENCES package_assignments (id) ON DELETE CASCADE,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX package_assignment_subaccounts_assignment_node_key ON package_assignment_subaccounts (assignment_id, routed_node_id);

--bun:split

CREATE UNIQUE INDEX package_assignment_subaccounts_node_email_key ON package_assignment_subaccounts (routed_node_id, email);

--bun:split

CREATE INDEX package_assignment_subaccounts_email_idx ON package_assignment_subaccounts (email);

--bun:split

CREATE INDEX package_assignment_subaccounts_username_idx ON package_assignment_subaccounts (username);

--bun:split

CREATE TABLE proxy_provider_configs (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  external_subscription_id BIGINT NOT NULL,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'http',
  interval BIGINT NOT NULL DEFAULT 3600,
  proxy TEXT NOT NULL DEFAULT 'DIRECT',
  size_limit BIGINT NOT NULL DEFAULT 0,
  header TEXT,
  health_check_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  health_check_url TEXT NOT NULL DEFAULT 'https://www.gstatic.com/generate_204',
  health_check_interval BIGINT NOT NULL DEFAULT 300,
  health_check_timeout BIGINT NOT NULL DEFAULT 5000,
  health_check_lazy BOOLEAN NOT NULL DEFAULT FALSE,
  health_check_expected_status BIGINT NOT NULL DEFAULT 204,
  filter TEXT,
  exclude_filter TEXT,
  exclude_type TEXT,
  geo_ip_filter TEXT,
  override TEXT,
  process_mode TEXT NOT NULL DEFAULT 'client',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (external_subscription_id) REFERENCES external_subscriptions (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX proxy_provider_configs_username_idx ON proxy_provider_configs (username);

--bun:split

CREATE INDEX proxy_provider_configs_external_subscription_id_idx ON proxy_provider_configs (external_subscription_id);

--bun:split

CREATE TABLE renewal_requests (
  id BIGSERIAL PRIMARY KEY,
  request_token TEXT NOT NULL,
  username TEXT NOT NULL,
  telegram_id BIGINT NOT NULL DEFAULT 0,
  package_id BIGINT NOT NULL,
  assignment_id BIGINT,
  package_name TEXT NOT NULL DEFAULT '',
  previous_end_date TIMESTAMPTZ,
  renew_days BIGINT NOT NULL,
  passphrase TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'web',
  status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by BIGINT NOT NULL DEFAULT 0,
  reviewed_at TIMESTAMPTZ,
  new_end_date TIMESTAMPTZ,
  error_message TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (assignment_id) REFERENCES package_assignments (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX renewal_requests_request_token_key ON renewal_requests (request_token);

--bun:split

CREATE INDEX renewal_requests_user_created_idx ON renewal_requests (username, created_at);

--bun:split

CREATE UNIQUE INDEX renewal_requests_pending_user_key ON renewal_requests (username) WHERE status IN ('pending', 'processing');

--bun:split

CREATE TABLE routing_rule_presets (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  name TEXT NOT NULL,
  rule_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX routing_rule_presets_username_rule_key ON routing_rule_presets (username, rule_json);

--bun:split

CREATE INDEX routing_rule_presets_username_updated_idx ON routing_rule_presets (username, updated_at);

--bun:split

CREATE TABLE sessions (
  token_hash TEXT NOT NULL,
  username TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (token_hash),
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE INDEX sessions_username_idx ON sessions (username);

--bun:split

CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

--bun:split

CREATE TABLE tasks (
  id BIGSERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT,
  source TEXT NOT NULL CHECK (source IN ('system', 'admin')),
  dedup_key TEXT NOT NULL DEFAULT '',
  alert_id BIGINT,
  evidence_id BIGINT,
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'claimed', 'done', 'cancelled')),
  claimed_by BIGINT,
  lease_until TIMESTAMPTZ,
  cancel_reason TEXT,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (alert_id) REFERENCES alerts (id) ON DELETE SET NULL,
  FOREIGN KEY (evidence_id) REFERENCES evidence_packages (id) ON DELETE SET NULL,
  FOREIGN KEY (claimed_by) REFERENCES api_tokens (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX tasks_dedup_key_active ON tasks (dedup_key) WHERE status IN ('open', 'claimed') AND dedup_key <> '';

--bun:split

CREATE TABLE traffic_daily_external_subscriptions (
  external_subscription_id BIGINT NOT NULL,
  date TEXT NOT NULL,
  uplink BIGINT NOT NULL DEFAULT 0,
  downlink BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (external_subscription_id, date),
  FOREIGN KEY (external_subscription_id) REFERENCES external_subscriptions (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX traffic_daily_external_subscriptions_date_idx ON traffic_daily_external_subscriptions (date);

--bun:split

CREATE TABLE user_inbound_configs (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  server_id BIGINT NOT NULL,
  inbound_tag TEXT NOT NULL,
  protocol TEXT NOT NULL,
  credential_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX user_inbound_configs_key ON user_inbound_configs (username, server_id, inbound_tag);

--bun:split

CREATE TABLE user_outbounds (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  server_id BIGINT NOT NULL,
  inbound_tag TEXT NOT NULL,
  outbound_tag TEXT NOT NULL,
  outbound_json JSONB NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE
);

--bun:split

CREATE TABLE user_settings (
  username TEXT NOT NULL,
  force_sync_external BOOLEAN NOT NULL DEFAULT FALSE,
  match_rule TEXT NOT NULL DEFAULT 'node_name',
  cache_expire_minutes BIGINT NOT NULL DEFAULT 0,
  sync_traffic BOOLEAN NOT NULL DEFAULT FALSE,
  sync_scope TEXT NOT NULL DEFAULT 'saved_only',
  keep_node_name BOOLEAN NOT NULL DEFAULT FALSE,
  custom_rules_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  enable_short_link BOOLEAN NOT NULL DEFAULT FALSE,
  use_new_template_system BOOLEAN NOT NULL DEFAULT FALSE,
  enable_proxy_provider BOOLEAN NOT NULL DEFAULT FALSE,
  node_name_filter TEXT NOT NULL DEFAULT '剩余|流量|到期|订阅|时间|重置',
  node_order JSONB NOT NULL DEFAULT '[]',
  default_template_filename TEXT NOT NULL DEFAULT '',
  append_sub_info BOOLEAN NOT NULL DEFAULT FALSE,
  debug_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  debug_log_path TEXT NOT NULL DEFAULT '',
  debug_started_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username),
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE TABLE user_subaccounts (
  id BIGSERIAL PRIMARY KEY,
  username TEXT NOT NULL,
  routed_node_id BIGINT NOT NULL,
  email TEXT NOT NULL,
  credential_json JSONB NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX user_subaccounts_node_user_key ON user_subaccounts (routed_node_id, username);

--bun:split

CREATE UNIQUE INDEX user_subaccounts_node_email_key ON user_subaccounts (routed_node_id, email);

--bun:split

CREATE INDEX user_subaccounts_email_idx ON user_subaccounts (email);

--bun:split

CREATE INDEX user_subaccounts_username_idx ON user_subaccounts (username);

--bun:split

CREATE TABLE user_subscriptions (
  username TEXT NOT NULL,
  subscription_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username, subscription_id),
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE,
  FOREIGN KEY (subscription_id) REFERENCES subscribe_files (id) ON DELETE CASCADE
);

--bun:split

CREATE INDEX user_subscriptions_username_idx ON user_subscriptions (username);

--bun:split

CREATE INDEX user_subscriptions_subscription_id_idx ON user_subscriptions (subscription_id);

--bun:split

CREATE TABLE user_tokens (
  username TEXT NOT NULL,
  token TEXT NOT NULL,
  user_short_code TEXT NOT NULL DEFAULT '',
  custom_user_short_code TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (username),
  FOREIGN KEY (username) REFERENCES users (username) ON DELETE CASCADE
);

--bun:split

CREATE UNIQUE INDEX user_tokens_user_short_code_key ON user_tokens (user_short_code) WHERE user_short_code <> '';

--bun:split

CREATE UNIQUE INDEX user_tokens_custom_user_short_code_key ON user_tokens (custom_user_short_code) WHERE custom_user_short_code <> '';

--bun:split

CREATE TABLE websites (
  id BIGSERIAL PRIMARY KEY,
  server_id BIGINT NOT NULL,
  domain TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('static', 'proxy', 'decoy')),
  target TEXT NOT NULL DEFAULT '',
  certificate_id BIGINT,
  use_443 BOOLEAN NOT NULL DEFAULT FALSE,
  scanned JSONB NOT NULL DEFAULT '{}',
  managed BOOLEAN NOT NULL DEFAULT FALSE,
  conf_path TEXT NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resource_version BIGINT NOT NULL DEFAULT 1,
  deleted_at TIMESTAMPTZ,
  FOREIGN KEY (server_id) REFERENCES servers (id) ON DELETE CASCADE,
  FOREIGN KEY (certificate_id) REFERENCES certificates (id) ON DELETE SET NULL
);

--bun:split

CREATE UNIQUE INDEX websites_server_domain_key ON websites (server_id, domain);
