// Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.

package model

import (
	"encoding/json"
	"time"

	"github.com/uptrace/bun"
)

// AlertDelivery 对应表 alert_deliveries。
type AlertDelivery struct {
	bun.BaseModel `bun:"table:alert_deliveries"`

	AlertID    int64 `bun:"alert_id,pk"`
	DeliveryID int64 `bun:"delivery_id,pk"`
}

// Alert 对应表 alerts（kind Alert，action）。
type Alert struct {
	bun.BaseModel `bun:"table:alerts"`

	ID              int64           `bun:"id,pk,autoincrement"`
	Category        string          `bun:"category"`
	Level           string          `bun:"level"`
	ObjectKind      string          `bun:"object_kind"`
	ObjectID        string          `bun:"object_id"`
	DedupKey        string          `bun:"dedup_key"`
	Conditions      json.RawMessage `bun:"conditions"`
	EvidenceID      *int64          `bun:"evidence_id"`
	Status          string          `bun:"status"`
	ResolveReason   *string         `bun:"resolve_reason"`
	OccurrenceCount int64           `bun:"occurrence_count"`
	FirstSeenAt     time.Time       `bun:"first_seen_at"`
	LastSeenAt      time.Time       `bun:"last_seen_at"`
	CreatedAt       time.Time       `bun:"created_at"`
	UpdatedAt       time.Time       `bun:"updated_at"`
	ResourceVersion int64           `bun:"resource_version"`
	DeletedAt       *time.Time      `bun:"deleted_at"`
}

// AuditLog 对应表 audit_logs（kind AuditLog，system），append-only。
type AuditLog struct {
	bun.BaseModel `bun:"table:audit_logs"`

	ID          int64     `bun:"id,pk,autoincrement"`
	At          time.Time `bun:"at"`
	Actor       string    `bun:"actor"`
	ActorKind   string    `bun:"actor_kind"`
	TokenID     *int64    `bun:"token_id"`
	Command     string    `bun:"command"`
	ArgsDigest  string    `bun:"args_digest"`
	FullCommand *string   `bun:"full_command"`
	Output      *string   `bun:"output"`
	PlanID      *int64    `bun:"plan_id"`
	Result      string    `bun:"result"`
}

// AutomationRule 对应表 automation_rules（kind AutomationRule，config）。
type AutomationRule struct {
	bun.BaseModel `bun:"table:automation_rules"`

	ID              int64           `bun:"id,pk,autoincrement"`
	Name            string          `bun:"name"`
	Trigger         string          `bun:"trigger"`
	Condition       json.RawMessage `bun:"condition"`
	Action          string          `bun:"action"`
	MaxTargets      *int64          `bun:"max_targets"`
	DeadlineMinutes *int64          `bun:"deadline_minutes"`
	Enabled         bool            `bun:"enabled"`
	ProposedBy      string          `bun:"proposed_by"`
	Status          string          `bun:"status"`
	ApprovedBy      *string         `bun:"approved_by"`
	ApprovedAt      *time.Time      `bun:"approved_at"`
	CreatedAt       time.Time       `bun:"created_at"`
	UpdatedAt       time.Time       `bun:"updated_at"`
	ResourceVersion int64           `bun:"resource_version"`
	DeletedAt       *time.Time      `bun:"deleted_at"`
}

// BatchOpCounter 对应表 batch_op_counters，append-only。
type BatchOpCounter struct {
	bun.BaseModel `bun:"table:batch_op_counters"`

	ID      int64     `bun:"id,pk,autoincrement"`
	TokenID *int64    `bun:"token_id"`
	Actor   string    `bun:"actor"`
	At      time.Time `bun:"at"`
	Objects int64     `bun:"objects"`
	Command string    `bun:"command"`
}

// ConfigSnapshot 对应表 config_snapshots（kind ConfigSnapshot，system），append-only。
type ConfigSnapshot struct {
	bun.BaseModel `bun:"table:config_snapshots"`

	ID            int64           `bun:"id,pk,autoincrement"`
	ObjectKind    string          `bun:"object_kind"`
	ObjectID      int64           `bun:"object_id"`
	ObjectVersion int64           `bun:"object_version"`
	Content       json.RawMessage `bun:"content"`
	ContentHash   string          `bun:"content_hash"`
	Source        string          `bun:"source"`
	Status        string          `bun:"status"`
	ApplyID       *string         `bun:"apply_id"`
	CreatedAt     time.Time       `bun:"created_at"`
}

// EvidencePackage 对应表 evidence_packages（kind EvidencePackage，system）。
type EvidencePackage struct {
	bun.BaseModel `bun:"table:evidence_packages"`

	ID           int64           `bun:"id,pk,autoincrement"`
	Category     string          `bun:"category"`
	ServerID     *int64          `bun:"server_id"`
	CollectedAt  time.Time       `bun:"collected_at"`
	Items        json.RawMessage `bun:"items"`
	CollectError *string         `bun:"collect_error"`
	SizeBytes    int64           `bun:"size_bytes"`
	ExpiresAt    *time.Time      `bun:"expires_at"`
	CreatedAt    time.Time       `bun:"created_at"`
	UpdatedAt    time.Time       `bun:"updated_at"`
}

// Job 对应表 jobs（kind Job，action）。
type Job struct {
	bun.BaseModel `bun:"table:jobs"`

	ID              int64           `bun:"id,pk,autoincrement"`
	JobID           string          `bun:"job_id"`
	Kind            string          `bun:"kind"`
	ServerID        *int64          `bun:"server_id"`
	Args            json.RawMessage `bun:"args"`
	Status          string          `bun:"status"`
	StartedAt       *time.Time      `bun:"started_at"`
	FinishedAt      *time.Time      `bun:"finished_at"`
	ExitCode        *int64          `bun:"exit_code"`
	Output          *string         `bun:"output"`
	OutputTruncated bool            `bun:"output_truncated"`
	CreatedAt       time.Time       `bun:"created_at"`
	UpdatedAt       time.Time       `bun:"updated_at"`
	ResourceVersion int64           `bun:"resource_version"`
	DeletedAt       *time.Time      `bun:"deleted_at"`
}

// NotifyChannel 对应表 notify_channels（kind NotifyChannel，config）。
type NotifyChannel struct {
	bun.BaseModel `bun:"table:notify_channels"`

	ID              int64           `bun:"id,pk,autoincrement"`
	Name            string          `bun:"name"`
	Type            string          `bun:"type"`
	Events          json.RawMessage `bun:"events"`
	Enabled         bool            `bun:"enabled"`
	Target          string          `bun:"target"`
	Secret          string          `bun:"secret"`
	LastDeliveredAt *time.Time      `bun:"last_delivered_at"`
	LastError       *string         `bun:"last_error"`
	CreatedAt       time.Time       `bun:"created_at"`
	UpdatedAt       time.Time       `bun:"updated_at"`
	ResourceVersion int64           `bun:"resource_version"`
	DeletedAt       *time.Time      `bun:"deleted_at"`
}

// NotifyDelivery 对应表 notify_deliveries（kind NotifyDelivery，system）。
type NotifyDelivery struct {
	bun.BaseModel `bun:"table:notify_deliveries"`

	ID            int64           `bun:"id,pk,autoincrement"`
	DeliveryID    string          `bun:"delivery_id"`
	ChannelID     int64           `bun:"channel_id"`
	Type          string          `bun:"type"`
	Payload       json.RawMessage `bun:"payload"`
	Attempts      int64           `bun:"attempts"`
	Status        string          `bun:"status"`
	LastError     *string         `bun:"last_error"`
	LastAttemptAt *time.Time      `bun:"last_attempt_at"`
	CreatedAt     time.Time       `bun:"created_at"`
	UpdatedAt     time.Time       `bun:"updated_at"`
}

// Plan 对应表 plans（kind Plan，action）。
type Plan struct {
	bun.BaseModel `bun:"table:plans"`

	ID              int64           `bun:"id,pk,autoincrement"`
	Objects         json.RawMessage `bun:"objects"`
	Diff            json.RawMessage `bun:"diff"`
	AffectedCount   int64           `bun:"affected_count"`
	ShareIdentity   *string         `bun:"share_identity"`
	ShareScope      json.RawMessage `bun:"share_scope"`
	ExpiresAt       time.Time       `bun:"expires_at"`
	Status          string          `bun:"status"`
	ApplyID         *string         `bun:"apply_id"`
	CreatedAt       time.Time       `bun:"created_at"`
	UpdatedAt       time.Time       `bun:"updated_at"`
	ResourceVersion int64           `bun:"resource_version"`
	DeletedAt       *time.Time      `bun:"deleted_at"`
}

// Task 对应表 tasks（kind Task，action）。
type Task struct {
	bun.BaseModel `bun:"table:tasks"`

	ID              int64      `bun:"id,pk,autoincrement"`
	Title           string     `bun:"title"`
	Body            *string    `bun:"body"`
	Source          string     `bun:"source"`
	DedupKey        string     `bun:"dedup_key"`
	AlertID         *int64     `bun:"alert_id"`
	EvidenceID      *int64     `bun:"evidence_id"`
	Status          string     `bun:"status"`
	ClaimedBy       *int64     `bun:"claimed_by"`
	LeaseUntil      *time.Time `bun:"lease_until"`
	CancelReason    *string    `bun:"cancel_reason"`
	ExpiresAt       *time.Time `bun:"expires_at"`
	CreatedAt       time.Time  `bun:"created_at"`
	UpdatedAt       time.Time  `bun:"updated_at"`
	ResourceVersion int64      `bun:"resource_version"`
	DeletedAt       *time.Time `bun:"deleted_at"`
}
