// Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.

package v1

import (
	"encoding/json"
	"time"
)

// AlertSpec 是 kind Alert（action）的 spec 字段。
type AlertSpec struct {
	Category   string `json:"category"`
	Level      string `json:"level"`
	ObjectKind string `json:"object_kind"`
	ObjectID   string `json:"object_id"`
	DedupKey   string `json:"dedup_key"`
}

// AlertStatus 是 kind Alert 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type AlertStatus struct {
	Conditions      json.RawMessage `json:"conditions"`
	EvidenceID      *int64          `json:"evidence_id"`
	Status          string          `json:"status"`
	ResolveReason   *string         `json:"resolve_reason"`
	OccurrenceCount int64           `json:"occurrence_count"`
	FirstSeenAt     time.Time       `json:"first_seen_at"`
	LastSeenAt      time.Time       `json:"last_seen_at"`
}

// AuditLogSpec 是 kind AuditLog（system）的 spec 字段。
type AuditLogSpec struct {
	At          time.Time `json:"at"`
	Actor       string    `json:"actor"`
	ActorKind   string    `json:"actor_kind"`
	TokenID     *int64    `json:"token_id"`
	Command     string    `json:"command"`
	ArgsDigest  string    `json:"args_digest"`
	FullCommand *string   `json:"full_command"`
	Output      *string   `json:"output"`
	PlanID      *int64    `json:"plan_id"`
	Result      string    `json:"result"`
}

// AuditLogStatus 是 kind AuditLog 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type AuditLogStatus struct{}

// AutomationRuleSpec 是 kind AutomationRule（config）的 spec 字段。
type AutomationRuleSpec struct {
	Name            string          `json:"name"`
	Trigger         string          `json:"trigger"`
	Condition       json.RawMessage `json:"condition"`
	Action          string          `json:"action"`
	MaxTargets      *int64          `json:"max_targets"`
	DeadlineMinutes *int64          `json:"deadline_minutes"`
	Enabled         bool            `json:"enabled"`
}

// AutomationRuleStatus 是 kind AutomationRule 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type AutomationRuleStatus struct {
	ProposedBy string     `json:"proposed_by"`
	Status     string     `json:"status"`
	ApprovedBy *string    `json:"approved_by"`
	ApprovedAt *time.Time `json:"approved_at"`
}

// ConfigSnapshotSpec 是 kind ConfigSnapshot（system）的 spec 字段。
type ConfigSnapshotSpec struct {
	ObjectKind    string          `json:"object_kind"`
	ObjectID      int64           `json:"object_id"`
	ObjectVersion int64           `json:"object_version"`
	Content       json.RawMessage `json:"content"`
	ContentHash   string          `json:"content_hash"`
	Source        string          `json:"source"`
	Status        string          `json:"status"`
	ApplyID       *string         `json:"apply_id"`
}

// ConfigSnapshotStatus 是 kind ConfigSnapshot 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type ConfigSnapshotStatus struct{}

// EvidencePackageSpec 是 kind EvidencePackage（system）的 spec 字段。
type EvidencePackageSpec struct {
	Category string `json:"category"`
	ServerID *int64 `json:"server_id"`
}

// EvidencePackageStatus 是 kind EvidencePackage 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type EvidencePackageStatus struct {
	CollectedAt  time.Time       `json:"collected_at"`
	Items        json.RawMessage `json:"items"`
	CollectError *string         `json:"collect_error"`
	SizeBytes    int64           `json:"size_bytes"`
	ExpiresAt    *time.Time      `json:"expires_at"`
}

// JobSpec 是 kind Job（action）的 spec 字段。
type JobSpec struct {
	JobID    string          `json:"job_id"`
	Kind     string          `json:"kind"`
	ServerID *int64          `json:"server_id"`
	Args     json.RawMessage `json:"args"`
}

// JobStatus 是 kind Job 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type JobStatus struct {
	Status          string     `json:"status"`
	StartedAt       *time.Time `json:"started_at"`
	FinishedAt      *time.Time `json:"finished_at"`
	ExitCode        *int64     `json:"exit_code"`
	Output          *string    `json:"output"`
	OutputTruncated bool       `json:"output_truncated"`
}

// NotifyChannelSpec 是 kind NotifyChannel（config）的 spec 字段。
type NotifyChannelSpec struct {
	Name    string          `json:"name"`
	Type    string          `json:"type"`
	Events  json.RawMessage `json:"events"`
	Enabled bool            `json:"enabled"`
}

// NotifyChannelStatus 是 kind NotifyChannel 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type NotifyChannelStatus struct {
	Target          string     `json:"target"`
	Secret          string     `json:"secret"`
	LastDeliveredAt *time.Time `json:"last_delivered_at"`
	LastError       *string    `json:"last_error"`
}

// NotifyDeliverySpec 是 kind NotifyDelivery（system）的 spec 字段。
type NotifyDeliverySpec struct {
	DeliveryID string          `json:"delivery_id"`
	ChannelID  int64           `json:"channel_id"`
	Type       string          `json:"type"`
	Payload    json.RawMessage `json:"payload"`
}

// NotifyDeliveryStatus 是 kind NotifyDelivery 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type NotifyDeliveryStatus struct {
	Attempts      int64      `json:"attempts"`
	Status        string     `json:"status"`
	LastError     *string    `json:"last_error"`
	LastAttemptAt *time.Time `json:"last_attempt_at"`
}

// PlanSpec 是 kind Plan（action）的 spec 字段。
type PlanSpec struct {
	Objects       json.RawMessage `json:"objects"`
	Diff          json.RawMessage `json:"diff"`
	AffectedCount int64           `json:"affected_count"`
	ShareIdentity *string         `json:"share_identity"`
	ShareScope    json.RawMessage `json:"share_scope"`
	ExpiresAt     time.Time       `json:"expires_at"`
}

// PlanStatus 是 kind Plan 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type PlanStatus struct {
	Status  string  `json:"status"`
	ApplyID *string `json:"apply_id"`
}

// TaskSpec 是 kind Task（action）的 spec 字段。
type TaskSpec struct {
	Title      string  `json:"title"`
	Body       *string `json:"body"`
	Source     string  `json:"source"`
	DedupKey   string  `json:"dedup_key"`
	AlertID    *int64  `json:"alert_id"`
	EvidenceID *int64  `json:"evidence_id"`
}

// TaskStatus 是 kind Task 的 status 字段：status、动作专属、人类专属、主控自身类与只读，apply 一律拒收。
type TaskStatus struct {
	Status       string     `json:"status"`
	ClaimedBy    *int64     `json:"claimed_by"`
	LeaseUntil   *time.Time `json:"lease_until"`
	CancelReason *string    `json:"cancel_reason"`
	ExpiresAt    *time.Time `json:"expires_at"`
}

// generatedKinds 是 kind 清单，Kinds、Lookup、KindsOf 与 DecodeSpec 都查它。
var generatedKinds = []KindInfo{
	{
		Name:         "Alert",
		Class:        ClassAction,
		SpecFields:   []string{"category", "level", "object_kind", "object_id", "dedup_key"},
		StatusFields: []string{"conditions", "evidence_id", "status", "resolve_reason", "occurrence_count", "first_seen_at", "last_seen_at"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "conditions": "status", "evidence_id": "status", "status": "status", "resolve_reason": "status", "occurrence_count": "status", "first_seen_at": "status", "last_seen_at": "status", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
	{
		Name:         "AuditLog",
		Class:        ClassSystem,
		SpecFields:   []string{"at", "actor", "actor_kind", "token_id", "command", "args_digest", "full_command", "output", "plan_id", "result"},
		StatusFields: []string{},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta"},
	},
	{
		Name:         "AutomationRule",
		Class:        ClassConfig,
		SpecFields:   []string{"name", "trigger", "condition", "action", "max_targets", "deadline_minutes", "enabled"},
		StatusFields: []string{"proposed_by", "status", "approved_by", "approved_at"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "proposed_by": "action", "status": "human", "approved_by": "human", "approved_at": "human", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
	{
		Name:         "ConfigSnapshot",
		Class:        ClassSystem,
		SpecFields:   []string{"object_kind", "object_id", "object_version", "content", "content_hash", "source", "status", "apply_id"},
		StatusFields: []string{},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "created_at": "meta"},
	},
	{
		Name:         "EvidencePackage",
		Class:        ClassSystem,
		SpecFields:   []string{"category", "server_id"},
		StatusFields: []string{"collected_at", "items", "collect_error", "size_bytes", "expires_at"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "collected_at": "status", "items": "status", "collect_error": "status", "size_bytes": "status", "expires_at": "status", "created_at": "meta", "updated_at": "meta"},
	},
	{
		Name:         "Job",
		Class:        ClassAction,
		SpecFields:   []string{"job_id", "kind", "server_id", "args"},
		StatusFields: []string{"status", "started_at", "finished_at", "exit_code", "output", "output_truncated"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "status": "status", "started_at": "status", "finished_at": "status", "exit_code": "status", "output": "status", "output_truncated": "status", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
	{
		Name:         "NotifyChannel",
		Class:        ClassConfig,
		SpecFields:   []string{"name", "type", "events", "enabled"},
		StatusFields: []string{"target", "secret", "last_delivered_at", "last_error"},
		MaskedFields: []string{"secret"},
		notApplyable: map[string]string{"id": "meta", "target": "master_self", "secret": "master_self", "last_delivered_at": "status", "last_error": "status", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
	{
		Name:         "NotifyDelivery",
		Class:        ClassSystem,
		SpecFields:   []string{"delivery_id", "channel_id", "type", "payload"},
		StatusFields: []string{"attempts", "status", "last_error", "last_attempt_at"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "attempts": "status", "status": "status", "last_error": "status", "last_attempt_at": "status", "created_at": "meta", "updated_at": "meta"},
	},
	{
		Name:         "Plan",
		Class:        ClassAction,
		SpecFields:   []string{"objects", "diff", "affected_count", "share_identity", "share_scope", "expires_at"},
		StatusFields: []string{"status", "apply_id"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "status": "status", "apply_id": "status", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
	{
		Name:         "Task",
		Class:        ClassAction,
		SpecFields:   []string{"title", "body", "source", "dedup_key", "alert_id", "evidence_id"},
		StatusFields: []string{"status", "claimed_by", "lease_until", "cancel_reason", "expires_at"},
		MaskedFields: []string{},
		notApplyable: map[string]string{"id": "meta", "status": "action", "claimed_by": "action", "lease_until": "action", "cancel_reason": "status", "expires_at": "status", "created_at": "meta", "updated_at": "meta", "resource_version": "meta", "deleted_at": "meta"},
	},
}
