package schema

import (
	"fmt"
	"strings"
)

// Dialect 是目标数据库方言。
type Dialect int

const (
	SQLite Dialect = iota + 1
	Postgres
)

func (d Dialect) String() string {
	switch d {
	case SQLite:
		return "sqlite"
	case Postgres:
		return "postgres"
	}
	return fmt.Sprintf("Dialect(%d)", int(d))
}

// 四类类型表达写死在这里（design 第 3 条），DDL 里不出现别的类型词。
var (
	sqliteTypes = map[Type]string{
		TypeSerial: "INTEGER", TypeInt: "INTEGER", TypeFloat: "REAL", TypeBool: "BOOLEAN",
		TypeTime: "TEXT", TypeJSON: "TEXT", TypeText: "TEXT", TypeBlob: "BLOB",
	}
	postgresTypes = map[Type]string{
		TypeSerial: "BIGINT", TypeInt: "BIGINT", TypeFloat: "DOUBLE PRECISION", TypeBool: "BOOLEAN",
		TypeTime: "TIMESTAMPTZ", TypeJSON: "JSONB", TypeText: "TEXT", TypeBlob: "BYTEA",
	}
)

// TypeName 返回列类型在某方言里的写法。自增主键在 DDL 里另有完整写法（见 columnDDL），
// 这里给的是它建成后在库里的类型，供元数据反查比对。
func TypeName(t Type, d Dialect) string {
	switch d {
	case SQLite:
		return sqliteTypes[t]
	case Postgres:
		return postgresTypes[t]
	}
	return ""
}

// SplitMarker 是 bun/migrate 在一个 SQL 文件里分隔语句的标记。
const SplitMarker = "--bun:split"

// DDL 生成整个注册表在某方言下的建表 SQL，表按外键拓扑排序。
func DDL(r *Registry, d Dialect) string {
	var b strings.Builder
	b.WriteString("-- Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.\n")
	b.WriteString("-- 方言：" + d.String() + "。表结构的唯一来源是 internal/base/schema 的注册表，改表先改注册表再重新生成。\n")
	first := true
	for _, t := range r.Tables() {
		for _, stmt := range tableDDL(t, d) {
			if !first {
				b.WriteString("\n" + SplitMarker + "\n")
			}
			first = false
			b.WriteString("\n" + stmt + "\n")
		}
	}
	return b.String()
}

func tableDDL(t *Table, d Dialect) []string {
	pk := t.PKColumns()
	serialPK := ""
	if len(pk) == 1 {
		if c, ok := t.Column(pk[0]); ok && c.Type == TypeSerial {
			serialPK = pk[0]
		}
	}
	var lines []string
	for _, c := range t.Columns {
		lines = append(lines, "  "+columnDDL(c, d, c.Name == serialPK))
	}
	if serialPK == "" {
		lines = append(lines, "  PRIMARY KEY ("+strings.Join(pk, ", ")+")")
	}
	for _, fk := range t.ForeignKeys {
		s := fmt.Sprintf("  FOREIGN KEY (%s) REFERENCES %s (%s)",
			strings.Join(fk.Columns, ", "), fk.RefTable, strings.Join(fk.RefColumns, ", "))
		if fk.OnUpdate != "" {
			s += " ON UPDATE " + fk.OnUpdate
		}
		if fk.OnDelete != "" {
			s += " ON DELETE " + fk.OnDelete
		}
		lines = append(lines, s)
	}
	stmts := []string{"CREATE TABLE " + t.Name + " (\n" + strings.Join(lines, ",\n") + "\n);"}
	for _, ix := range t.Indexes {
		s := "CREATE "
		if ix.Unique {
			s += "UNIQUE "
		}
		s += "INDEX " + ix.Name + " ON " + t.Name + " (" + strings.Join(ix.Columns, ", ") + ")"
		if ix.Where != "" {
			s += " WHERE " + ix.Where
		}
		stmts = append(stmts, s+";")
	}
	return stmts
}

func columnDDL(c Column, d Dialect, serialPK bool) string {
	if serialPK {
		if d == SQLite {
			return c.Name + " INTEGER PRIMARY KEY AUTOINCREMENT"
		}
		return c.Name + " BIGSERIAL PRIMARY KEY"
	}
	s := c.Name + " " + TypeName(c.Type, d)
	if !c.Nullable {
		s += " NOT NULL"
	}
	if c.Default != "" {
		s += " DEFAULT " + c.Default
	}
	for _, check := range c.Checks() {
		s += " CHECK (" + check + ")"
	}
	return s
}
