package schema

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

const generatedHeader = "// Code generated by go run ./internal/base/schema/cmd/gen; DO NOT EDIT.\n"

var initialisms = map[string]string{
	"id": "ID", "url": "URL", "ip": "IP", "json": "JSON", "dns": "DNS", "tls": "TLS", "api": "API", "uuid": "UUID",
}

// GoName 把 snake_case 的列名转成 Go 的导出名：dedup_key → DedupKey，alert_id → AlertID。
func GoName(snake string) string {
	parts := strings.Split(snake, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		if up, ok := initialisms[p]; ok {
			parts[i] = up
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// goType 返回列在 Go 结构体里的类型：可空列用指针，JSON 用 json.RawMessage，二进制用 []byte。
func goType(c Column) string {
	var base string
	switch c.Type {
	case TypeSerial, TypeInt:
		base = "int64"
	case TypeFloat:
		base = "float64"
	case TypeBool:
		base = "bool"
	case TypeTime:
		base = "time.Time"
	case TypeJSON:
		base = "json.RawMessage"
	case TypeText:
		base = "string"
	case TypeBlob:
		base = "[]byte"
	}
	if c.Nullable && c.Type != TypeJSON && c.Type != TypeBlob {
		return "*" + base
	}
	return base
}

func sortedByName(tables []*Table) []*Table {
	out := append([]*Table(nil), tables...)
	sort.Slice(out, func(i, j int) bool { return out[i].Name < out[j].Name })
	return out
}

func writeImports(b *bytes.Buffer, cols []Column, extra ...string) {
	needJSON, needTime := false, false
	for _, c := range cols {
		switch c.Type {
		case TypeJSON:
			needJSON = true
		case TypeTime:
			needTime = true
		}
	}
	var std []string
	if needJSON {
		std = append(std, `"encoding/json"`)
	}
	if needTime {
		std = append(std, `"time"`)
	}
	if len(std) == 0 && len(extra) == 0 {
		return
	}
	b.WriteString("import (\n")
	for _, s := range std {
		b.WriteString("\t" + s + "\n")
	}
	if len(std) > 0 && len(extra) > 0 {
		b.WriteString("\n")
	}
	for _, s := range extra {
		b.WriteString("\t" + s + "\n")
	}
	b.WriteString(")\n\n")
}

// GenerateModels 生成 internal/base/model/zz_generated.go：每张表一个 bun 模型。
func GenerateModels(r *Registry) ([]byte, error) {
	tables := sortedByName(r.Tables())
	var all []Column
	for _, t := range tables {
		all = append(all, t.Columns...)
	}
	var b bytes.Buffer
	b.WriteString(generatedHeader + "\npackage model\n\n")
	writeImports(&b, all, `"github.com/uptrace/bun"`)
	for _, t := range tables {
		fmt.Fprintf(&b, "// %s 对应表 %s", t.GoName, t.Name)
		if t.IsKind() {
			fmt.Fprintf(&b, "（kind %s，%s）", t.Kind, t.KindClass)
		}
		if t.AppendOnly {
			b.WriteString("，append-only")
		}
		b.WriteString("。\n")
		fmt.Fprintf(&b, "type %s struct {\n\tbun.BaseModel `bun:\"table:%s\"`\n\n", t.GoName, t.Name)
		pk := map[string]bool{}
		for _, col := range t.PKColumns() {
			pk[col] = true
		}
		for _, c := range t.Columns {
			tag := c.Name
			if pk[c.Name] {
				tag += ",pk"
			}
			if c.Type == TypeSerial {
				tag += ",autoincrement"
			}
			fmt.Fprintf(&b, "\t%s %s `bun:\"%s\"`\n", GoName(c.Name), goType(c), tag)
		}
		b.WriteString("}\n\n")
	}
	return format.Source(b.Bytes())
}
